repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: pretty-format-json
      - id: detect-private-key
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        args : [--line-length=79]
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
        args:
          - -d unused-import
          - --ignore-imports=yes
          - -d duplicate-code
          - -d import-error
          - -d no-name-in-module
          - -d redefined-outer-name
          - -d no-else-return
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.7.1
    hooks:
      - id: reorder-python-imports