VENV = ../AudioVenv
PYTHON = $(VENV)/bin/python3
PIP = $(VENV)/bin/pip

$(VENV)/bin/activate: requirements.txt
 python3 -m venv $(VENV)
 $(PIP) install -r requirements.txt
 pre-commit install


clean:
 rm -rf __pycache__
 rm -rf $(VENV)
